//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itogovaya_peredelanaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказы покуп.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказыПокуп CustomAttributes)

    // *** End programmer edit section *** (ЗаказыПокуп CustomAttributes)
    [AutoAltered()]
    [Caption("Заказы покупателей")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказыПокупE", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Клиенты as \'Клиенты\'",
            "Клиенты.ФИО as \'ФИО клиента\'"}, Hidden=new string[] {
            "Клиенты.ФИО"})]
    [AssociatedDetailViewAttribute("ЗаказыПокупE", "ТЧЗаказПок", "ТЧЗаказПокE", true, "", "заказ покупателя", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказыПокупE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("ЗаказыПокупL", new string[] {
            "Номер as \'Номер\'",
            "Дата as \'Дата\'",
            "Клиенты.ФИО as \'ФИО\'"})]
    public class ЗаказыПокуп : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомер;
        
        private IIS.Itogovaya_peredelanaya.Клиенты fКлиенты;
        
        private IIS.Itogovaya_peredelanaya.DetailArrayOfТЧЗаказПок fТЧЗаказПок;
        
        // *** Start programmer edit section *** (ЗаказыПокуп CustomMembers)

        // *** End programmer edit section *** (ЗаказыПокуп CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказыПокуп.Дата CustomAttributes)

        // *** End programmer edit section *** (ЗаказыПокуп.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.Дата Get start)

                // *** End programmer edit section *** (ЗаказыПокуп.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ЗаказыПокуп.Дата Get end)

                // *** End programmer edit section *** (ЗаказыПокуп.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.Дата Set start)

                // *** End programmer edit section *** (ЗаказыПокуп.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ЗаказыПокуп.Дата Set end)

                // *** End programmer edit section *** (ЗаказыПокуп.Дата Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказыПокуп.Номер CustomAttributes)

        // *** End programmer edit section *** (ЗаказыПокуп.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.Номер Get start)

                // *** End programmer edit section *** (ЗаказыПокуп.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ЗаказыПокуп.Номер Get end)

                // *** End programmer edit section *** (ЗаказыПокуп.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.Номер Set start)

                // *** End programmer edit section *** (ЗаказыПокуп.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ЗаказыПокуп.Номер Set end)

                // *** End programmer edit section *** (ЗаказыПокуп.Номер Set end)
            }
        }
        
        /// <summary>
        /// Заказы покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказыПокуп.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ЗаказыПокуп.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.Клиенты Get start)

                // *** End programmer edit section *** (ЗаказыПокуп.Клиенты Get start)
                IIS.Itogovaya_peredelanaya.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ЗаказыПокуп.Клиенты Get end)

                // *** End programmer edit section *** (ЗаказыПокуп.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.Клиенты Set start)

                // *** End programmer edit section *** (ЗаказыПокуп.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ЗаказыПокуп.Клиенты Set end)

                // *** End programmer edit section *** (ЗаказыПокуп.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Заказы покуп.
        /// </summary>
        // *** Start programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок CustomAttributes)

        // *** End programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок CustomAttributes)
        public virtual IIS.Itogovaya_peredelanaya.DetailArrayOfТЧЗаказПок ТЧЗаказПок
        {
            get
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Get start)

                // *** End programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Get start)
                if ((this.fТЧЗаказПок == null))
                {
                    this.fТЧЗаказПок = new IIS.Itogovaya_peredelanaya.DetailArrayOfТЧЗаказПок(this);
                }
                IIS.Itogovaya_peredelanaya.DetailArrayOfТЧЗаказПок result = this.fТЧЗаказПок;
                // *** Start programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Get end)

                // *** End programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Set start)

                // *** End programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Set start)
                this.fТЧЗаказПок = value;
                // *** Start programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Set end)

                // *** End programmer edit section *** (ЗаказыПокуп.ТЧЗаказПок Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказыПокупE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыПокупE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыПокупE", typeof(IIS.Itogovaya_peredelanaya.ЗаказыПокуп));
                }
            }
            
            /// <summary>
            /// "ЗаказыПокупL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказыПокупL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказыПокупL", typeof(IIS.Itogovaya_peredelanaya.ЗаказыПокуп));
                }
            }
        }
    }
}
