//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itogovaya_peredelanaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Заказ пост.
    /// </summary>
    // *** Start programmer edit section *** (ЗаказПост CustomAttributes)

    // *** End programmer edit section *** (ЗаказПост CustomAttributes)
    [AutoAltered()]
    [Caption("Заказ поставщику")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ЗаказПостE", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Менеджер as \'Ответственный\'",
            "Менеджер.Сотрудники.ФИО as \'Ответственный\'",
            "Организации as \'Организации\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'"}, Hidden=new string[] {
            "Организации.Организация",
            "Склады.Склад",
            "Контрагенты.Контрагент"})]
    [AssociatedDetailViewAttribute("ЗаказПостE", "ТЧЗаказ", "ТЧЗаказE", true, "", "Т ч заказ", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ЗаказПостE", "Менеджер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ЗаказПостE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ЗаказПостE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [MasterViewDefineAttribute("ЗаказПостE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [View("ЗаказПостL", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "СостОтгрузки as \'Сост отгрузки\'",
            "СостояниеОплаты as \'Состояние оплаты\'",
            "СуммаВклНДС as \'Сумма вкл НДС\'",
            "СуммаДокумента as \'Сумма документа\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'",
            "Контрагенты.Контрагент as \'Контрагент\'"})]
    public class ЗаказПост : IIS.Itogovaya_peredelanaya.ОтчетОЗак
    {
        
        // *** Start programmer edit section *** (ЗаказПост CustomMembers)

        // *** End programmer edit section *** (ЗаказПост CustomMembers)

        
        // *** Start programmer edit section *** (ЗаказПост.Заполнить CustomAttributes)

        // *** End programmer edit section *** (ЗаказПост.Заполнить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Заполнить()
        {
            // *** Start programmer edit section *** (ЗаказПост.Заполнить method implementation)

            return;
            // *** End programmer edit section *** (ЗаказПост.Заполнить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ЗаказПостE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказПостE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказПостE", typeof(IIS.Itogovaya_peredelanaya.ЗаказПост));
                }
            }
            
            /// <summary>
            /// "ЗаказПостL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ЗаказПостL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ЗаказПостL", typeof(IIS.Itogovaya_peredelanaya.ЗаказПост));
                }
            }
        }
    }
}
