//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itogovaya_peredelanaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Менеджер.
    /// </summary>
    // *** Start programmer edit section *** (Менеджер CustomAttributes)

    // *** End programmer edit section *** (Менеджер CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("МенеджерE", new string[] {
            "Сотрудники as \'Сотрудники\'",
            "Сотрудники.ФИО as \'ФИО\'",
            "Сотрудники.Должности.Должность as \'Должность\'"}, Hidden=new string[] {
            "Сотрудники.ФИО"})]
    [MasterViewDefineAttribute("МенеджерE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИО")]
    [View("МенеджерL", new string[] {
            "Сотрудники.ФИО as \'ФИО\'"})]
    public class Менеджер : ICSSoft.STORMNET.DataObject
    {
        
        private IIS.Itogovaya_peredelanaya.Сотрудники fСотрудники;
        
        // *** Start programmer edit section *** (Менеджер CustomMembers)

        // *** End programmer edit section *** (Менеджер CustomMembers)

        
        /// <summary>
        /// Менеджер.
        /// </summary>
        // *** Start programmer edit section *** (Менеджер.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (Менеджер.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (Менеджер.Сотрудники Get start)

                // *** End programmer edit section *** (Менеджер.Сотрудники Get start)
                IIS.Itogovaya_peredelanaya.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (Менеджер.Сотрудники Get end)

                // *** End programmer edit section *** (Менеджер.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Менеджер.Сотрудники Set start)

                // *** End programmer edit section *** (Менеджер.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (Менеджер.Сотрудники Set end)

                // *** End programmer edit section *** (Менеджер.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "МенеджерE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МенеджерE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МенеджерE", typeof(IIS.Itogovaya_peredelanaya.Менеджер));
                }
            }
            
            /// <summary>
            /// "МенеджерL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View МенеджерL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("МенеджерL", typeof(IIS.Itogovaya_peredelanaya.Менеджер));
                }
            }
        }
    }
}
