//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itogovaya_peredelanaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// План закупок.
    /// </summary>
    // *** Start programmer edit section *** (ПланЗакупок CustomAttributes)

    // *** End programmer edit section *** (ПланЗакупок CustomAttributes)
    [AutoAltered()]
    [Caption("План закупок")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ПланЗакупокE", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "ДатаОкончания as \'Дата окончания\'",
            "Менеджер as \'Менеджер\'",
            "Организации as \'Организации\'",
            "Менеджер.Сотрудники.ФИО as \'Ответственный\'",
            "Организации.Организация as \'Организация\'",
            "Склады as \'Склады\'",
            "Склады.Склад as \'Склад\'",
            "Контрагенты as \'Контрагенты\'",
            "Контрагенты.Контрагент as \'Контрагент\'"}, Hidden=new string[] {
            "Организации.Организация",
            "Склады.Склад",
            "Контрагенты.Контрагент"})]
    [AssociatedDetailViewAttribute("ПланЗакупокE", "План", "ПланE", true, "", "План", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ПланЗакупокE", "Менеджер", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "")]
    [MasterViewDefineAttribute("ПланЗакупокE", "Организации", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Организация")]
    [MasterViewDefineAttribute("ПланЗакупокE", "Склады", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Склад")]
    [MasterViewDefineAttribute("ПланЗакупокE", "Контрагенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Контрагент")]
    [View("ПланЗакупокL", new string[] {
            "Номер as \'Номер\'",
            "ДатаНачала as \'Дата начала\'",
            "Организации.Организация as \'Организация\'",
            "Склады.Склад as \'Склад\'",
            "Контрагенты.Контрагент as \'Контрагент\'",
            "ДатаОкончания as \'Дата окончания\'"})]
    public class ПланЗакупок : ICSSoft.STORMNET.DataObject
    {
        
        private int fНомер;
        
        private System.DateTime fДатаНачала = System.DateTime.Now;
        
        private System.DateTime fДатаОкончания;
        
        private IIS.Itogovaya_peredelanaya.Организации fОрганизации;
        
        private IIS.Itogovaya_peredelanaya.Склады fСклады;
        
        private IIS.Itogovaya_peredelanaya.Менеджер fМенеджер;
        
        private IIS.Itogovaya_peredelanaya.Контрагенты fКонтрагенты;
        
        private IIS.Itogovaya_peredelanaya.DetailArrayOfПлан fПлан;
        
        // *** Start programmer edit section *** (ПланЗакупок CustomMembers)

        // *** End programmer edit section *** (ПланЗакупок CustomMembers)

        
        /// <summary>
        /// ДатаНачала.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.ДатаНачала CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.ДатаНачала CustomAttributes)
        public virtual System.DateTime ДатаНачала
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.ДатаНачала Get start)

                // *** End programmer edit section *** (ПланЗакупок.ДатаНачала Get start)
                System.DateTime result = this.fДатаНачала;
                // *** Start programmer edit section *** (ПланЗакупок.ДатаНачала Get end)

                // *** End programmer edit section *** (ПланЗакупок.ДатаНачала Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.ДатаНачала Set start)

                // *** End programmer edit section *** (ПланЗакупок.ДатаНачала Set start)
                this.fДатаНачала = value;
                // *** Start programmer edit section *** (ПланЗакупок.ДатаНачала Set end)

                // *** End programmer edit section *** (ПланЗакупок.ДатаНачала Set end)
            }
        }
        
        /// <summary>
        /// ДатаОкончания.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.ДатаОкончания CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.ДатаОкончания CustomAttributes)
        public virtual System.DateTime ДатаОкончания
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.ДатаОкончания Get start)

                // *** End programmer edit section *** (ПланЗакупок.ДатаОкончания Get start)
                System.DateTime result = this.fДатаОкончания;
                // *** Start programmer edit section *** (ПланЗакупок.ДатаОкончания Get end)

                // *** End programmer edit section *** (ПланЗакупок.ДатаОкончания Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.ДатаОкончания Set start)

                // *** End programmer edit section *** (ПланЗакупок.ДатаОкончания Set start)
                this.fДатаОкончания = value;
                // *** Start programmer edit section *** (ПланЗакупок.ДатаОкончания Set end)

                // *** End programmer edit section *** (ПланЗакупок.ДатаОкончания Set end)
            }
        }
        
        /// <summary>
        /// Номер.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.Номер CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.Номер CustomAttributes)
        public virtual int Номер
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.Номер Get start)

                // *** End programmer edit section *** (ПланЗакупок.Номер Get start)
                int result = this.fНомер;
                // *** Start programmer edit section *** (ПланЗакупок.Номер Get end)

                // *** End programmer edit section *** (ПланЗакупок.Номер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.Номер Set start)

                // *** End programmer edit section *** (ПланЗакупок.Номер Set start)
                this.fНомер = value;
                // *** Start programmer edit section *** (ПланЗакупок.Номер Set end)

                // *** End programmer edit section *** (ПланЗакупок.Номер Set end)
            }
        }
        
        /// <summary>
        /// План закупок.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.Контрагенты CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.Контрагенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Контрагенты"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Контрагенты Контрагенты
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.Контрагенты Get start)

                // *** End programmer edit section *** (ПланЗакупок.Контрагенты Get start)
                IIS.Itogovaya_peredelanaya.Контрагенты result = this.fКонтрагенты;
                // *** Start programmer edit section *** (ПланЗакупок.Контрагенты Get end)

                // *** End programmer edit section *** (ПланЗакупок.Контрагенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.Контрагенты Set start)

                // *** End programmer edit section *** (ПланЗакупок.Контрагенты Set start)
                this.fКонтрагенты = value;
                // *** Start programmer edit section *** (ПланЗакупок.Контрагенты Set end)

                // *** End programmer edit section *** (ПланЗакупок.Контрагенты Set end)
            }
        }
        
        /// <summary>
        /// План закупок.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.Менеджер CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.Менеджер CustomAttributes)
        [PropertyStorage(new string[] {
                "Менеджер"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Менеджер Менеджер
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.Менеджер Get start)

                // *** End programmer edit section *** (ПланЗакупок.Менеджер Get start)
                IIS.Itogovaya_peredelanaya.Менеджер result = this.fМенеджер;
                // *** Start programmer edit section *** (ПланЗакупок.Менеджер Get end)

                // *** End programmer edit section *** (ПланЗакупок.Менеджер Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.Менеджер Set start)

                // *** End programmer edit section *** (ПланЗакупок.Менеджер Set start)
                this.fМенеджер = value;
                // *** Start programmer edit section *** (ПланЗакупок.Менеджер Set end)

                // *** End programmer edit section *** (ПланЗакупок.Менеджер Set end)
            }
        }
        
        /// <summary>
        /// План закупок.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.Организации CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.Организации CustomAttributes)
        [PropertyStorage(new string[] {
                "Организации"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Организации Организации
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.Организации Get start)

                // *** End programmer edit section *** (ПланЗакупок.Организации Get start)
                IIS.Itogovaya_peredelanaya.Организации result = this.fОрганизации;
                // *** Start programmer edit section *** (ПланЗакупок.Организации Get end)

                // *** End programmer edit section *** (ПланЗакупок.Организации Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.Организации Set start)

                // *** End programmer edit section *** (ПланЗакупок.Организации Set start)
                this.fОрганизации = value;
                // *** Start programmer edit section *** (ПланЗакупок.Организации Set end)

                // *** End programmer edit section *** (ПланЗакупок.Организации Set end)
            }
        }
        
        /// <summary>
        /// План закупок.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.Склады CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.Склады CustomAttributes)
        [PropertyStorage(new string[] {
                "Склады"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Склады Склады
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.Склады Get start)

                // *** End programmer edit section *** (ПланЗакупок.Склады Get start)
                IIS.Itogovaya_peredelanaya.Склады result = this.fСклады;
                // *** Start programmer edit section *** (ПланЗакупок.Склады Get end)

                // *** End programmer edit section *** (ПланЗакупок.Склады Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.Склады Set start)

                // *** End programmer edit section *** (ПланЗакупок.Склады Set start)
                this.fСклады = value;
                // *** Start programmer edit section *** (ПланЗакупок.Склады Set end)

                // *** End programmer edit section *** (ПланЗакупок.Склады Set end)
            }
        }
        
        /// <summary>
        /// План закупок.
        /// </summary>
        // *** Start programmer edit section *** (ПланЗакупок.План CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.План CustomAttributes)
        public virtual IIS.Itogovaya_peredelanaya.DetailArrayOfПлан План
        {
            get
            {
                // *** Start programmer edit section *** (ПланЗакупок.План Get start)

                // *** End programmer edit section *** (ПланЗакупок.План Get start)
                if ((this.fПлан == null))
                {
                    this.fПлан = new IIS.Itogovaya_peredelanaya.DetailArrayOfПлан(this);
                }
                IIS.Itogovaya_peredelanaya.DetailArrayOfПлан result = this.fПлан;
                // *** Start programmer edit section *** (ПланЗакупок.План Get end)

                // *** End programmer edit section *** (ПланЗакупок.План Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ПланЗакупок.План Set start)

                // *** End programmer edit section *** (ПланЗакупок.План Set start)
                this.fПлан = value;
                // *** Start programmer edit section *** (ПланЗакупок.План Set end)

                // *** End programmer edit section *** (ПланЗакупок.План Set end)
            }
        }
        
        // *** Start programmer edit section *** (ПланЗакупок.Заполнить CustomAttributes)

        // *** End programmer edit section *** (ПланЗакупок.Заполнить CustomAttributes)
        [ICSSoft.STORMNET.AccessType(ICSSoft.STORMNET.AccessType.none)]
        public virtual void Заполнить()
        {
            // *** Start programmer edit section *** (ПланЗакупок.Заполнить method implementation)

            return;
            // *** End programmer edit section *** (ПланЗакупок.Заполнить method implementation)
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ПланЗакупокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланЗакупокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланЗакупокE", typeof(IIS.Itogovaya_peredelanaya.ПланЗакупок));
                }
            }
            
            /// <summary>
            /// "ПланЗакупокL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ПланЗакупокL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ПланЗакупокL", typeof(IIS.Itogovaya_peredelanaya.ПланЗакупок));
                }
            }
        }
    }
}
