//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Itogovaya_peredelanaya
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Т ч заказ пок.
    /// </summary>
    // *** Start programmer edit section *** (ТЧЗаказПок CustomAttributes)

    // *** End programmer edit section *** (ТЧЗаказПок CustomAttributes)
    [AutoAltered()]
    [Caption("Т ч заказ пок")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТЧЗаказПокE", new string[] {
            "Количество as \'Количество\'",
            "Номенклатура as \'Номенклатура\'",
            "Номенклатура.Номенклатура as \'Номенклатура\'"}, Hidden=new string[] {
            "Номенклатура.Номенклатура"})]
    [MasterViewDefineAttribute("ТЧЗаказПокE", "Номенклатура", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Номенклатура")]
    public class ТЧЗаказПок : ICSSoft.STORMNET.DataObject
    {
        
        private int fКоличество;
        
        private IIS.Itogovaya_peredelanaya.Номенклатура fНоменклатура;
        
        private IIS.Itogovaya_peredelanaya.ЗаказыПокуп fЗаказыПокуп;
        
        // *** Start programmer edit section *** (ТЧЗаказПок CustomMembers)

        // *** End programmer edit section *** (ТЧЗаказПок CustomMembers)

        
        /// <summary>
        /// Количество.
        /// </summary>
        // *** Start programmer edit section *** (ТЧЗаказПок.Количество CustomAttributes)

        // *** End programmer edit section *** (ТЧЗаказПок.Количество CustomAttributes)
        public virtual int Количество
        {
            get
            {
                // *** Start programmer edit section *** (ТЧЗаказПок.Количество Get start)

                // *** End programmer edit section *** (ТЧЗаказПок.Количество Get start)
                int result = this.fКоличество;
                // *** Start programmer edit section *** (ТЧЗаказПок.Количество Get end)

                // *** End programmer edit section *** (ТЧЗаказПок.Количество Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧЗаказПок.Количество Set start)

                // *** End programmer edit section *** (ТЧЗаказПок.Количество Set start)
                this.fКоличество = value;
                // *** Start programmer edit section *** (ТЧЗаказПок.Количество Set end)

                // *** End programmer edit section *** (ТЧЗаказПок.Количество Set end)
            }
        }
        
        /// <summary>
        /// Т ч заказ пок.
        /// </summary>
        // *** Start programmer edit section *** (ТЧЗаказПок.Номенклатура CustomAttributes)

        // *** End programmer edit section *** (ТЧЗаказПок.Номенклатура CustomAttributes)
        [PropertyStorage(new string[] {
                "Номенклатура"})]
        [NotNull()]
        public virtual IIS.Itogovaya_peredelanaya.Номенклатура Номенклатура
        {
            get
            {
                // *** Start programmer edit section *** (ТЧЗаказПок.Номенклатура Get start)

                // *** End programmer edit section *** (ТЧЗаказПок.Номенклатура Get start)
                IIS.Itogovaya_peredelanaya.Номенклатура result = this.fНоменклатура;
                // *** Start programmer edit section *** (ТЧЗаказПок.Номенклатура Get end)

                // *** End programmer edit section *** (ТЧЗаказПок.Номенклатура Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧЗаказПок.Номенклатура Set start)

                // *** End programmer edit section *** (ТЧЗаказПок.Номенклатура Set start)
                this.fНоменклатура = value;
                // *** Start programmer edit section *** (ТЧЗаказПок.Номенклатура Set end)

                // *** End programmer edit section *** (ТЧЗаказПок.Номенклатура Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Itogovaya_peredelanaya.ЗаказыПокуп.
        /// </summary>
        // *** Start programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп CustomAttributes)

        // *** End programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "ЗаказыПокуп"})]
        public virtual IIS.Itogovaya_peredelanaya.ЗаказыПокуп ЗаказыПокуп
        {
            get
            {
                // *** Start programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Get start)

                // *** End programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Get start)
                IIS.Itogovaya_peredelanaya.ЗаказыПокуп result = this.fЗаказыПокуп;
                // *** Start programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Get end)

                // *** End programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Set start)

                // *** End programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Set start)
                this.fЗаказыПокуп = value;
                // *** Start programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Set end)

                // *** End programmer edit section *** (ТЧЗаказПок.ЗаказыПокуп Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТЧЗаказПокE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТЧЗаказПокE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТЧЗаказПокE", typeof(IIS.Itogovaya_peredelanaya.ТЧЗаказПок));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of ТЧЗаказПок.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfТЧЗаказПок CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfТЧЗаказПок CustomAttributes)
    public class DetailArrayOfТЧЗаказПок : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Itogovaya_peredelanaya.DetailArrayOfТЧЗаказПок members)

        // *** End programmer edit section *** (IIS.Itogovaya_peredelanaya.DetailArrayOfТЧЗаказПок members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type ТЧЗаказПок by index.
        /// </summary>
        /// <summary>
        /// Adds object with type ТЧЗаказПок.
        /// </summary>
        public DetailArrayOfТЧЗаказПок(IIS.Itogovaya_peredelanaya.ЗаказыПокуп fЗаказыПокуп) : 
                base(typeof(ТЧЗаказПок), ((ICSSoft.STORMNET.DataObject)(fЗаказыПокуп)))
        {
        }
        
        public IIS.Itogovaya_peredelanaya.ТЧЗаказПок this[int index]
        {
            get
            {
                return ((IIS.Itogovaya_peredelanaya.ТЧЗаказПок)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Itogovaya_peredelanaya.ТЧЗаказПок dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
